### ISSUE TITLE
Error VueBlurHash componenet not registered

### ISSUE THREAD

**Issue by daletom** [damienroche/vue-blurhash#10]
Hi, this is the error I was getting:
` 19:5  error  The "VueBlurHash" component has been registered but not used  vue/no-unused-components`

This is what's on my home page: 
```
<template>
  <div class="home">
    <blur-hash-image
      width="400"
      height="300"
      hash="LdHfL}oJR$WBKnfi%3ofT0kCM{ay"
      src="https://images.unsplash.com/photo-1545910684-8e7c081be9b0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1867&q=80"
      alt="green lawn grass during daytime"
    />
  </div>
</template>

<script>
import VueBlurHash from "vue-blurhash";

export default {
  name: "Home",
  components: {
    VueBlurHash
  }
};
```
and here is the main.js
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import VueBlurHash from "vue-blurhash";

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");

Vue.use(VueBlurHash);
```

Do you see a glaring mistake I made?  Or do you have a live website example and code I could fork or look at?  Thanks so much! Here is the github if that helps as well: https://github.com/daletom/blurhash-ex

**Comment by damienroche** [comment]
@daletom you don't have to import VueBlurHash in your `Home.vue` file. You already imported it in `main.js` and registred it via `Vue.use()` function

**Comment by daletom** [comment]
Thanks for that @damienroche . It's now saying `Unknown custom element: <blur-hash-image> - did you register the component correctly?`

Do I need to export it somehow in the main.js file with the name blur-hash-image?

If I run npm run serve, this is what it looks like when I inspect: 

```
<blur-hash-image width="400" height="300" hash="LdHfL}oJR$WBKnfi%3ofT0kCM{ay" src="https://images.unsplash.com/photo-1545910684-8e7c081be9b0?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1867&amp;q=80" alt="green lawn grass during daytime"></blur-hash-image>
```

**Comment by damienroche** [comment]
@daletom it's because you call `Vue.use()` function after create a new Vue Instance. 
Just move the `Vue.use()` line before `new Vue({...})`

**Comment by daletom** [comment]
🤦  Thanks so much Damien
