### ISSUE TITLE
Width stuck at 0 when using Vuetify

### ISSUE THREAD

**Issue by michaeltoohig** [damienroche/vue-blurhash#4]
First off thanks for the package, I had my own implementation before but yours is cleaner so I'm trying it out.

I'm using Vuetify for a project and when I use the `<blur-hash-image>` component on its own in a `<v-flex>` or even inside an `<avatar>` component it doesn't show anything on screen. It appears that the width is somehow set to 0 even though I explicitly set the width and height.

If I put the blur-hash-image component inside a `<v-card>` then the image shows up. Not sure what that is about but I would guess something is interfering with the css?

This has a canvas of width 0
```
<v-container>
        <v-layout row>
          <v-flex d-flex justify-end md4 sm6 sx12>
            <blur-hash-image
              :width="200"
              :height="200"
              :hash="foo.blurhash"
              :src="foo.thumbnail"
              alt=""
            />
          </v-flex>
     </v-layout>
</v-container>
```

This has a card with an image filling the width of the card not following the width defined on the blurhash image component.
```
<v-container>
        <v-layout row>
          <v-flex d-flex justify-end md4 sm6 sx12>
            <v-card
              class="mr-3"
              width="500"
              tile
            >
              <blur-hash-image
                :width="200"
                :height="200"
                :hash="image_src(vehicle).blurhash"
                :src="image_src(vehicle).thumbnail"
                alt=""
              />
            </v-card>
          </v-flex>
     </v-layout>
</v-container>
```

**Comment by damienroche** [comment]
@michaeltoohig are you still stuck with this ? Can you provide me an repo or live example so I can reproduce

**Comment by michaeltoohig** [comment]
Thanks for returning, I believe I found a work around but its been a while. I'll take a look at what I did (or didn't do) and try to create the example you asked for.

**Comment by michaeltoohig** [comment]
@damienroche as far as I can tell now the issue was the blurhash image component's interaction with Vuetify. The blurhash canvas plays nicely with vuetify avatar component but not the full BlurHashComponent.

This issue probably sits on my own shoulders if I want these two to interact together nicely. But just to show how I got here.

```
vue create test-app
cd test-app
vue add vuetify
```
Then I replaced `HelloWorld.vue` with the following
```
<template>
  <v-container>
    <v-avatar>
      <blur-hash-image
        :width="48"
        :height="48"
        :hash="hash"
        :src="src"
        :transitionDuration="duration"
      ></blur-hash-image>
    </v-avatar>
    <blur-hash-image
      :width="200"
      :height="200"
      :hash="hash"
      :src="src"
      :transitionDuration="duration"
    ></blur-hash-image>
    <v-avatar>
      <blur-hash-canvas
        :hash="hash"
        :width="48"
        :height="48"
        :punch="1"
      />
    </v-avatar>
  </v-container>
</template>

<script>
import { BlurHashCanvas } from "vue-blurhash";

export default {
  name: 'HelloWorld',
  components: {
    'blur-hash-canvas': BlurHashCanvas,
  },
  data: () => ({
    hash: "LEHV6nWB2yk8pyo0adR*.7kCMdnj",
    src: "https://via.placeholder.com/150/0000FF/808080 ?Text=Digital.com",
    duration: 2000,
  }),
}
</script>
```

![image](https://user-images.githubusercontent.com/34083701/103948339-bbec5b80-518d-11eb-9a60-89610237d831.png)

You can see the blurhash canvas works but the blurhash image has 0 width in the avatar element. Probably because it's a `div` and not an `image` as expected by the avatar component.
